### ISSUE TITLE
Shalrath without horns

### ISSUE THREAD

**Issue by Greenwood72** [NightFright2k19/quake_authmdl#1]
Hello, NightFright. I noticed that TribalQuake was using a hornless version of Chillo's shalrath during his YouTube playthroughs. I asked him about it and he told me that he had altered the model via QME.

My brief discussion and the link he provided to this hornless shalrath model can be found here: https://www.youtube.com/watch?v=7s0kEjTK9d8&t=428s

I enjoy what you have collected here and just thought that you might be interested! :)

**Comment by NightFright2k19** [comment]
It is implemented with final v1.8. Thanks a lot for this hint! Maybe eventually Chillo will make his own variation, but for now this will do.
