### ISSUE TITLE
Grenade launcher model

### ISSUE THREAD

**Issue by e20norr** [NightFright2k19/quake_authmdl#10]
This is some great stuff! However, there is one thing that could make this mod even better, in my opinion.

Please switch the grenade launcher model to either Dwerve's model or the 2021 remastered model. The current one deviates way too much from the other models, and it's not very pretty to look at either.

**Comment by NightFright2k19** [comment]
Everybody has their own preferences. We have had enough positive feedback for the current model to keep it in place. Also, we only have a replacement for the SoA Prox Mine Launcher that fits the current launcher, not any of the others out there. On top of that, it was hard work to get muzzle flashes added which are missing on other variants.

Feel free to revert to Rev.20 (where we added the Dwere models) or take the GL model from there and replace it in your personal copy of our latest pak files if you don't want to lose all the other changes we made in the meantime. It isn't that hard to figure it out.
