### ISSUE TITLE
Issue with Map "Ravisod" / Engine Quakespasm Spiked win 64 dev latest version.

### ISSUE THREAD

**Issue by GenericJohnDoeNO0** [NightFright2k19/quake_authmdl#5]
Hi, i do not know if this pack (the progs.dat maybe) of my problem, but if used with the Ravisod Map (new on quaddicted) and quakespasm spiked (map was designed for that engine) in the first level the "laser trap" goes into rapid fire mode, somehow the trigger on that map gets overwritten so that the lasers are constantly blasting. I did try to message the author of the map via the release review page about this problem, but could you have a look at this issue, too?

**Comment by NightFright2k19** [comment]
Latest QSS builds are highly unstable and can cause all kinds of issues. These cannot be used as a base for this mod and I don't provide support for them. 

I recommend using regular Quakespasm builds at this point in general or at least a QSS build from earlier this year (August or earlier).

Anyway, you can still try playing without the new progs.dat and see if it fixes the issue. It is entirely optional and the models will work fine without it.
