### ISSUE TITLE
Mjolnir seam

### ISSUE THREAD

**Issue by Hexaae** [NightFright2k19/quake_authmdl#6]
Playing with https://github.com/andrei-drexler/ironwail Mjolinr 3d mesh has a ugly seam (original mesh seems broken).
Would be great if you can fix it.

![ironwail0000](https://user-images.githubusercontent.com/8591462/155859289-6fc4c0d0-0adf-430a-a2f0-0be64b1a67cd.png)

**Comment by NightFright2k19** [comment]
Probably a port issue. We didn't even create a new model for this.

**Comment by Hexaae** [comment]
Maybe I'm wrong, but I'm afraid it's not a port issue since I can see something strange also with other ports, even though there is no seam there...
Looks like a texture too small or badly wrapping but just for coincidence it looks "acceptable" with original game engine or some modern ports, and worse for others....

**Comment by Hexaae** [comment]
![image](https://user-images.githubusercontent.com/8591462/155879948-37076930-5392-4407-8687-832b22b95d46.png)
https://quake.fandom.com/wiki/Mjolnir
Indeed also with original engine it has a strange 3d mesh, revealing a longitudinal seam... probably hidden by approximation. Also metal surface seems to have a stretched texture...

Can you suggest me a tutorial how to modify Quake weapons/items (using blender...?)? I could try to fix it by myself.

**Comment by NightFright2k19** [comment]
For questions about mdl editing, I am unfortunately not the right person to talk to. My knowledge pretty much ends with skin editing. None of the mdls in our mod have been done by myself, just the bsp models.

I have yet to confirm this issue on my side, but I cannot remember ever seeing this. If it had offended me, it would probably have been fixed early on during this project. Maybe you are lucky and either osj or Tea Monster are still active over at the QuakeOne forums. Otherwise, the Func_Msgboard would still be a place where active modellers or at least "insiders" might be found.

**UPDATE:**
Checked ingame in Ironwail and the seam is indeed there. Dunno if a model edit is needed for that, though. Maybe it can be solved with a skin edit.

**Comment by Hexaae** [comment]
Yep, not sure but maybe just enlarging texture could do the trick covering the gap... not sure how will look in 8-bit RAW though in this case: https://github.com/andrei-drexler/ironwail/issues/51

I've read there was indeed a 3D editor for Quake 1 QME 3.1 (Quake Model Editor): https://www.reddit.com/r/quake/comments/h7hwam/good_model_viewereditor_for_quake_1/fuljikk/?utm_source=reddit&utm_medium=web2x&context=3
https://www.youtube.com/watch?v=uMSxznEVoqU

**Comment by NightFright2k19** [comment]
I think a skin edit is the only way to fix this in OpenGL without breaking it in software mode. That's something I can try, it's just about 2-3 extra pixel lines on the texture as gapfiller, probably. We did this also for the shotguns and it made all the seams effectively invisible.

QME is one tool I was also using, it works for people like me with basic knowledge when it's about simple models like weapons that don't have complex structures and low amount of frames.

It's worth giving it a shot, so I will reopen this for now.

**Comment by NightFright2k19** [comment]
Skin fix to cover the seam has been applied. Please download current build (Code --> Download Zip) and see if the matter is resolved. It is on my end. (That overstretched texture on the top part will still be there, but the seam was certainly the bigger issue for that model.)

At the same time, I have also placed all progs.dat files in pak files to address a different issue (some ports not being able to read external progs.dat files).

**Comment by Hexaae** [comment]
👍🏻 well done! Decent also in 8-bit "raw" mode (original texture/tone mapping mode),

Normal mode:
![ironwail000](https://user-images.githubusercontent.com/8591462/155953415-427094e6-ecc3-4f9b-bcdf-9329438d6dd5.png)

Ironwail 8-bit RAW (has a vertical overlapping line but it's ok since was the same with the original engine):
![ironwail001](https://user-images.githubusercontent.com/8591462/155953446-e5a12f3d-4191-495d-bc30-12c36ce871f6.png)

**Comment by NightFright2k19** [comment]
Alright. We can consider this one resolved, then.
