### ISSUE TITLE
Decapitated head too large

### ISSUE THREAD

**Issue by Hexaae** [NightFright2k19/quake_authmdl#8]
My impression or the decapitated heads are too large compared to the normal head size of fallen enemies?
Would be possible a resize fix for those heads?
![ironwail006](https://user-images.githubusercontent.com/8591462/156904120-ca737fba-9d1b-450c-a70d-2c90b0a95fc0.png)

**Comment by NightFright2k19** [comment]
Their size is based on the original models. They should have the right size.

I will make another size comparison with the original model, but we were pretty thorough regarding that. It might be deceiving since the helmet part is a bit larger than before.

**Comment by NightFright2k19** [comment]
So here is a direct model comparison of the original head vs the new one. As you can see, our new model is wider since more detail and volume has been added to the helmet. Note also how the dimensions of the head part itself remain accurate, and actually shrinking the whole model would make it wrong compared to the original. I must say that we are spot on with this one and I see no reason to change anything about it.

![head_comparison](https://user-images.githubusercontent.com/54737241/156916353-1a730ba3-e6e9-44f9-97fe-26d4353efa4a.png)

**Comment by Hexaae** [comment]
I mean the original model was too big, not your fault with the more detailed new model. Compare it to the head of not decapitated soldier, that's what I meant 😉
Resized to 0.8 or 0.7 would fix this, compared to original game too where it was too big. In the pic above you can see a dead soldier on the left and on the right a decapitated head which looks the head of a "giant" compared to the original soldier model.
I noticed this first time I found a corpse with the head of another dismembered enemy aside.

In red a mockup how the correct size should be.
![ovo](https://user-images.githubusercontent.com/8591462/156917460-de9bcd8a-1077-476e-8244-d7a5e1d412ee.png)

**Comment by NightFright2k19** [comment]
Alright, didn't get that part with the original mdl being wrong. Did a quick resize with QME, not a big deal. Test the following to see what fits better:
- pakz07.pak contains head @ 0.7x scale
- pakz08.pak contains head @ 0.8x scale

Ofc you will have to rename the pak file name so it has the highest number in your id1 folder.

[headtest.zip](https://github.com/NightFright2k19/quake_authmdl/files/8192339/headtest.zip)

**Comment by Hexaae** [comment]
Great! 👍🏻
0.7 is just fine IMHO (maybe 0.71-0.72 would be perfect?):
![ironwail003](https://user-images.githubusercontent.com/8591462/156920523-44a1aacf-21c8-495e-bff1-9007203cae1c.png)

Here is a savegame for you to test (for hipnotic) and adjust the size: https://gofile.io/d/W1vAvd

P.S.
If I remember well also the other soldier with lasers can be dismembered... maybe that head size should be fixed too. Have to check that too.

**Comment by Hexaae** [comment]
Looks fine the laser guy IMHO, no need to resize that too:
![image](https://user-images.githubusercontent.com/8591462/156921229-5a44c164-4353-4aee-85b3-9a20c7cbd410.png)

**Comment by NightFright2k19** [comment]
Alright. Then here is another test file with the Grunt head resized to 0.72x scale. If that hits the spot, I can add it.
[paktest.zip](https://github.com/NightFright2k19/quake_authmdl/files/8192445/paktest.zip)

**Comment by Hexaae** [comment]
> Alright. Then here is another test file with the Grund head resized to 0.72x scale. If that hits the spot, I can add it. [paktest.zip](https://github.com/NightFright2k19/quake_authmdl/files/8192445/paktest.zip)

It's OK for me! 👍🏻

**Comment by Hexaae** [comment]
If you teach me which are the files I could check and adjust all dismembered heads by myself 😉

**Comment by NightFright2k19** [comment]
Fix is implemented and id1 pak has been updated with the latest commit.
I think the rest of the heads is OK. We were really working for a long time on them and a lot of resizing has already happened. The readme mentions exactly which files in the pak belong to which model.

**Comment by Hexaae** [comment]
Rescaled those I've found incorrect: dog ("Rottweiler"), mega (laser guy "Enforcer"), guard ("Grunt")
If you want to include them: -removed-

**Comment by NightFright2k19** [comment]
That file only contains a progs.dat, not any actual mdl.

**Comment by Hexaae** [comment]
Sorry, here is correct link: https://gofile.io/d/t0Je10

**Comment by Hexaae** [comment]
Wrong link sorry. Here is new file https://dropmefiles.com/dYwJt

**Comment by NightFright2k19** [comment]
Added with latest commit.
